Feature/task 2
Mazorakopf/movie-react-app pull request #2
Opened 2021-04-12 21:57 UTC by Mazorakopf

2021-04-13 22:07 UTC, Vladlan requested changes

2021-04-13 22:07 UTC, Vladlan commented on package.json
> +    "build:dev": "webpack --node-env development --config ./webpack",
Do you need this command? (If yes name particular case when it will be used)

2021-04-13 22:07 UTC, Vladlan commented on webpack/webpack.config.common.js
> +          use: 'url-loader'
1. Url-loader is deprecated for weback v5. Use 'asset modules'.
2. It is a really bad practise to encode all jpg and png to base64 (it increases their size). Consider to use 'url-loader' only for small images (`options: {limit: 8192}`).

2021-04-13 22:07 UTC, Vladlan commented on webpack/webpack.config.prd.js
> +  devtool: 'source-map',
Do you need devtool for production build?

2021-04-14 09:26 UTC, Mazorakopf commented on package.json
> +    "build:dev": "webpack --node-env development --config ./webpack",
We can use this command to build artifact for lower environments like PREPROD, DEV and others.

2021-04-14 09:38 UTC, Mazorakopf commented on webpack/webpack.config.prd.js
> +  devtool: 'source-map',
It is not necessary to have devtools in production, it may even be better to disable this functionality. But in the documentation of the webpack, they encourage to use [sorce-map](https://webpack.js.org/guides/production/#source-mapping). 

I found the styles of source-map allowed for production here: https://webpack.js.org/configuration/devtool/#devtool

2021-04-14 10:15 UTC, Mazorakopf commented on webpack/webpack.config.common.js
> +          use: 'url-loader'
Done

2021-04-15 10:00 UTC, Vladlan commented on webpack/webpack.config.prd.js
> +  devtool: 'source-map',
Ok

2021-04-15 10:16 UTC, Vladlan commented on package.json
> +    "build:dev": "webpack --node-env development --config ./webpack",
I understand what this command is doing, but can you name particular case when you will use it in this project?

2021-04-15 10:17 UTC, Vladlan approved these changes

2021-04-15 10:22 UTC, Mazorakopf commented on package.json
> +    "build:dev": "webpack --node-env development --config ./webpack",
In this project, I most likely will not use this command, since I have a command `npm run start:dev` for development

2021-04-15 10:33 UTC, merged