[Task-5] : Hooks
Mazorakopf/movie-react-app pull request #5
Opened 2021-05-25 21:16 UTC by Mazorakopf

2021-05-26 10:12 UTC, Vladlan requested changes
Also configure dev env to not have hashed css classes
![hased_classes](https://user-images.githubusercontent.com/20605638/119643057-fe07f800-be23-11eb-8dc2-fa1e1af10992.PNG)

2021-05-26 10:12 UTC, Vladlan commented on src/components/MovieList/index.js
> -            openEditWindow={() => props.openEditWindow(preview)}
const MovieList = ({ moviePreviews, open, clickCard}) => {

2021-05-26 10:12 UTC, Vladlan commented on src/components/MovieList/index.js
> +            open={props.open}
open -> onMovieCardOpened
clickCard -> onMovieCardClicked

2021-05-26 10:12 UTC, Vladlan commented on src/pages/MovieSearch/index.js
> +  if (action.type === 'add') {
'add', 'edit', etc move to consts

2021-05-26 10:12 UTC, Vladlan commented on src/components/MovieDetails/index.js
> +  genre: PropTypes.string.isRequired,
Not all props in propTypes

2021-05-26 10:12 UTC, Vladlan commented on src/components/MovieDetails/style.module.scss
> +@use '../../global' as g;
I do recommend to not have all style files named 'style.module.scss'

2021-05-26 10:12 UTC, Vladlan commented on src/components/MovieDetails/index.js
> +import styles from './style.module.scss';
import S from './style.module.scss';

2021-05-26 10:12 UTC, Vladlan commented on src/components/MovieModal/AddEditMovieModal.js
> +    <button className={styles.close} onClick={props.close} />
close -> closeMovieModal
styles.close -> S.closeBtn

2021-05-26 10:12 UTC, Vladlan commented on src/components/MovieModal/AddEditMovieModal.js
> +        onChange={props.change}
change -> onInputChanged

2021-05-26 10:12 UTC, Vladlan commented on src/components/MovieModal/AddEditMovieModal.js
> +      <button className={styles.resetBtn} onClick={props.reset}>
reset -> resetMovieModal

2021-05-26 10:12 UTC, Vladlan commented on src/components/MovieModal/AddEditMovieModal.js
> +      <button className={styles.submitBtn} onClick={props.submit}>
submit -> submitMovieModal

2021-05-26 10:12 UTC, Vladlan commented on src/components/MovieModal/index.js
> +export default ({ type, submit, close, selectedMovie = empty }) => {
Just selectedMovie = {} or if you really care about memory consumption rename to preselectedMovie or smth like that

2021-05-26 10:12 UTC, Vladlan commented on src/components/MovieModal/index.js
>      Array.from(document.querySelectorAll(`.${styles.modal} input`)).forEach(
Since a moment when use started use React you should not use document to reset inputs, find a way how to reset inputs with react

2021-05-26 10:12 UTC, Vladlan commented on src/components/MovieModal/index.js
> +  if (type === 'add' || type === 'edit') {
No magic strings, use consts

2021-05-26 10:12 UTC, Vladlan commented on src/core/MovieService.js
> +
const generateNextId = () => movies[movies.length - 1].id + 1 or use uuid library

2021-05-26 10:12 UTC, Vladlan commented on src/pages/MovieSearch/index.js
>          <Suspense fallback={<div>Loading...</div>}>
<div>Loading...</div> move to separate component

2021-05-27 21:29 UTC, Mazorakopf commented on src/components/MovieList/index.js
> -            openEditWindow={() => props.openEditWindow(preview)}
done

2021-05-27 21:29 UTC, Mazorakopf commented on src/components/MovieList/index.js
> +            open={props.open}
done

2021-05-27 21:29 UTC, Mazorakopf commented on src/components/MovieDetails/index.js
> +  genre: PropTypes.string.isRequired,
done

2021-05-27 21:29 UTC, Mazorakopf commented on src/components/MovieModal/index.js
> +export default ({ type, submit, close, selectedMovie = empty }) => {
doen

2021-05-27 21:29 UTC, Mazorakopf commented on src/pages/MovieSearch/index.js
> +  if (action.type === 'add') {
done

2021-05-27 21:30 UTC, Mazorakopf commented on src/components/MovieDetails/index.js
> +import styles from './style.module.scss';
done

2021-05-27 21:30 UTC, Mazorakopf commented on src/components/MovieModal/AddEditMovieModal.js
> +        onChange={props.change}
done

2021-05-28 09:46 UTC, Vladlan requested changes

2021-05-28 09:46 UTC, Vladlan commented on src/core/MovieService.js
> +const generateNextId = () => ++movies[movies.length - 1].id;
movies[movies.length - 1].id + 1

2021-05-28 09:46 UTC, Vladlan commented on src/pages/MovieSearch/index.js
> +    return { ...action };
No need for `else if` here
if () return
if () return
....
return

2021-05-28 09:46 UTC, Vladlan commented on src/components/MovieModal/index.js
> +  } else if (type === MovieModalType.DELETE) {
No need for else if

2021-06-07 19:44 UTC, merged