[Task-6] : Redux
Mazorakopf/movie-react-app pull request #6
Opened 2021-06-08 21:33 UTC by Mazorakopf

2021-06-09 09:53 UTC, Vladlan requested changes

2021-06-09 09:53 UTC, Vladlan commented on src/pages/MovieSearch/action.js
> +const getMovies = (query) => async (dispatch) => {
Is in this file you have actions or actionCreators? If yes rename file than.

2021-06-09 09:53 UTC, Vladlan commented on src/pages/MovieSearch/action.js
> +export const onInputChanged = (dispatch, { selectedMovie }) => (event) =>
All names should reflect what they will do with store. onInputChanged saying nothing about it

2021-06-09 09:53 UTC, Vladlan commented on src/pages/MovieSearch/action.js
> +    modalType,
dispatch should always receive an object {type: ..., payload:...}

2021-06-09 09:53 UTC, Vladlan commented on src/pages/MovieSearch/index.js
> +export default connect(mapStateToProps, mapDispatchToProps)(MovieSearch);
The main idea or redux is to reduce cases when you will pass props from one component to another. Use connect for other components too and remove props waterfall.

2021-06-09 09:53 UTC, Vladlan commented on src/components/MovieList/MovieNavBar/index.js
> +MovieNavBar.propTypes = {
App is not working because of this file

2021-06-09 09:53 UTC, Vladlan commented on src/pages/MovieSearch/action.js
> +const baseUrl = 'http://localhost:4000';
Add backend for you repo for this

2021-06-09 09:53 UTC, Vladlan commented on src/pages/MovieSearch/action.js
> +  const response = await fetch(url, { method: 'GET' });
How about to add error handling?

2021-06-10 21:12 UTC, Mazorakopf commented on src/pages/MovieSearch/action.js
> +export const onInputChanged = (dispatch, { selectedMovie }) => (event) =>
renamed to `changeSelectedMovie`

2021-06-10 21:12 UTC, Mazorakopf commented on src/components/MovieList/MovieNavBar/index.js
> +MovieNavBar.propTypes = {
fixed

2021-06-10 22:04 UTC, Mazorakopf commented on src/pages/MovieSearch/action.js
> +    modalType,
fixed

2021-06-10 22:05 UTC, Mazorakopf commented on src/pages/MovieSearch/action.js
> +const baseUrl = 'http://localhost:4000';
moved backend calls to api package

2021-06-15 22:38 UTC, Mazorakopf commented on src/pages/MovieSearch/action.js
> +  const response = await fetch(url, { method: 'GET' });
added

2021-06-17 18:08 UTC, merged